name: Node CI

on:
  push:
  schedule:
    - cron: '0 1 * * *' # run at 1 AM UTC

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test --reporter mocha-junit-reporter
      continue-on-error: true
    env:
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

  report:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Build with Maven
      run: mvn -B test --file test-results.xml
    - uses: ashley-taylor/junit-report-annotations-action@master
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
      if: always()
